# Generated by Django 4.2.4 on 2023-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_quick_scan_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Full_Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_full_scan", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="get_description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="get_ip_addr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_addr", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="spider_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_spider", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="quick_scan",
            name="start_quick_scan",
            field=models.BooleanField(),
        ),
    ]
